name: lint
on: [push, pull_request]
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.23.x" ]
    runs-on: ubuntu-latest
    name: "Lint (Go ${{matrix.go}})"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Install dependencies
        run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: -v

      - name: go vet
        run: |
            go vet -tags 'test' ./...

      - name: staticcheck
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck -tags 'test redis' ./...
